---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.5
  values:
    controller:
      replicaCount: 1
      service:
        loadBalancerIP: 10.13.1.10