---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: TO-BE-REPLACED
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1m0s
  values:
    controller:
      admissionWebhooks:
        patch:
          nodeSelector:
            beta.kubernetes.io/os: linux
      nodeSelector:
        beta.kubernetes.io/os: linux
      replicaCount: 2
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        loadBalancerIP: TO-BE-REPLACED
    defaultBackend:
      nodeSelector:
        beta.kubernetes.io/os: linux